[package]
name = "geocoder-abbreviations"
version = "0.1.0"
authors = ["Mapbox <info@mapbox.com>"]
edition = "2018"

[dependencies]
alphanumeric-sort = "1.0.6"
fancy-regex = "0.1.0"
lazy_static = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
