[package]
name = "geocoder-abbreviations"
version = "0.1.0"
license = "MIT"
description = "Geocoding Abbreviations classified by language and type"
authors = [
    "Mapbox <info@mapbox.com>",
    "Nick Ingalls <nick@ingalls.ca>"
]

edition = "2018"

[dependencies]
rust-embed="5.5.1"
alphanumeric-sort = "1.0.6"
fancy-regex = "0.1.0"
lazy_static = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
